apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "1"
  labels: 
    app: websocket-service
  name: websocket-service
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: websocket-service
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: websocket-service
    spec: 
      containers: 
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          name: websocket-service
          env:
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: JWT_ISSUER_URI
      restartPolicy: Always