apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: websocket-service
  sessionAffinity: None
  type: LoadBalancer