--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "1"
  labels: 
    app: websocket-service
  name: websocket-service
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: websocket-service
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: websocket-service
    spec: 
      containers: 
        - image: "urosvesic/websocket-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: websocket-service
          env:
            - name: JWT_ISSUER_URI
              value: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WEmesG720
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocket-service
  name: websocket-service
  namespace: default
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: websocket-service
  sessionAffinity: None
  type: LoadBalancer
  

