
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: europe-central2
  DEPLOYMENT_NAME: websocket-service
  IMAGE: websocket-service-image
  TAG: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{secrets.GKE_SA_KEY}}
        project_id: ${{secrets.GKE_PROJECT}}

    - name: Configure Docker
      run: |-
        gcloud --quiet auth configure-docker
        

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_ZONE" --project "$PROJECT_ID"

    - name: Download
      run: |-
        gcloud components install gke-gcloud-auth-plugin

    - name: Build docker image
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

    - name: Publish image to GCR
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

    - name: Set up Kustomize
      run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

    - name: Deploy
      run: |-
        # replacing the image name in the k8s template
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide



